### ISSUE TITLE
When logs are opened from the Simulators tool, current test session is inadvertently changed.

### ISSUE THREAD

**Issue by skbhaskarla** [usnistgov/iheos-toolkit2#410]

**Comment by iheos** [comment]
This can happen because of the way sims are inherited.  When you are in Test Session X you have any sims that exist in default in the list.  If you select a default sim and click on goto logs then the Test Session changes to default.  This is now a "backdoor" way of signing into the protected default Test Session (here I am testing in multi-user mode with default Test Session not set to default).

Default sims test logs should be publicly viewable. That's why they are in the default test session. 

This implies that the action in the simulators manager of opening the sim log has to have some special behavior.  

The "move" to default Test Session must be done in a way that only permits the sim log viewer to use it. Maybe a "READONLY" flag that affectively allows you to be in default test session without signing in but that status only applies within sim log viewer.  Your real test session has not changed.  This way if you open a new tool you are in your original test session.
